## Kommentare füge ich noch hinzu! Erstmal nur der Code.
### Auch die Reihenfolge kann sich noch ändern
#### Wichtig ist, dass alle Zellen über einer Zelle ausgeführt werden müssen, damit die Zellen darunter funktionieren!
#### Außerdem, können die lambda-Methoden eine Weile dauern

In [125]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import timedelta

In [126]:
boston_2018_data = pd.read_csv('resources/boston_2018.csv')
boston_2018_data.head(10)

,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type
0,2018-01-01 00:16:33,2018-01-01 00:23:01,178,107,MIT Pacific St at Purrington St,Ames St at Main St,643,Subscriber
1,2018-01-01 00:42:00,2018-01-01 00:46:25,78,225,Union Square - Somerville,Cambridge Dept. of Public Works -147 Hampshire...,1581,Subscriber
2,2018-01-01 00:42:44,2018-01-01 01:02:11,16,76,Back Bay T Stop - Dartmouth St at Stuart St,Central Sq Post Office / Cambridge City Hall a...,173,Subscriber
3,2018-01-01 00:56:50,2018-01-01 01:11:06,69,177,Coolidge Corner - Beacon St @ Centre St,University Park,1772,Subscriber
4,2018-01-01 01:07:54,2018-01-01 01:16:02,4,46,Tremont St at E Berkeley St,Christian Science Plaza - Massachusetts Ave at...,1183,Subscriber
5,2018-01-01 01:15:59,2018-01-01 01:17:21,31,186,Seaport Hotel - Congress St at Seaport Ln,Congress St at Northern Ave,1793,Subscriber
6,2018-01-01 01:35:37,2018-01-01 01:42:35,51,222,Washington St at Lenox St,Troy Boston,60,Subscriber
7,2018-01-01 01:35:46,2018-01-01 01:45:11,189,178,Kendall T,MIT Pacific St at Purrington St,371,Subscriber
8,2018-01-01 01:45:04,2018-01-01 01:53:40,108,176,Harvard University / SEAS Cruft-Pierce Halls a...,Lesley University,961,Subscriber
9,2018-01-01 01:56:58,2018-01-01 02:06:13,185,178,Third at Binney,MIT Pacific St at Purrington St,1286,Subscriber

In [127]:
len(boston_2018_data)-len(boston_2018_data.dropna())

0

In [128]:
boston_2018_data_clean = boston_2018_data.dropna(axis=0)
boston_2018_data_clean.head(1000000)

,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type
0,2018-01-01 00:16:33,2018-01-01 00:23:01,178,107,MIT Pacific St at Purrington St,Ames St at Main St,643,Subscriber
1,2018-01-01 00:42:00,2018-01-01 00:46:25,78,225,Union Square - Somerville,Cambridge Dept. of Public Works -147 Hampshire...,1581,Subscriber
2,2018-01-01 00:42:44,2018-01-01 01:02:11,16,76,Back Bay T Stop - Dartmouth St at Stuart St,Central Sq Post Office / Cambridge City Hall a...,173,Subscriber
3,2018-01-01 00:56:50,2018-01-01 01:11:06,69,177,Coolidge Corner - Beacon St @ Centre St,University Park,1772,Subscriber
4,2018-01-01 01:07:54,2018-01-01 01:16:02,4,46,Tremont St at E Berkeley St,Christian Science Plaza - Massachusetts Ave at...,1183,Subscriber
...,...,...,...,...,...,...,...,...
999995,2018-08-15 18:25:56.7200,2018-08-15 18:56:06.9810,35,32,Arch St at Franklin St,Landmark Center - Brookline Ave at Park Dr,838,Subscriber
999996,2018-08-15 18:25:55.7250,2018-08-15 18:32:33.6170,139,87,Dana Park,Harvard University Housing - 115 Putnam Ave at...,3189,Subscriber
999997,2018-08-15 18:25:58.2320,2018-08-15 18:32:30.2600,80,178,MIT Stata Center at Vassar St / Main St,MIT Pacific St at Purrington St,99,Subscriber
999998,2018-08-15 18:25:56.3940,2018-08-16 09:18:15.8990,52,36,Newbury St at Hereford St,Copley Square - Dartmouth St at Boylston St,3199,Subscriber
999999,2018-08-15 18:25:59.1560,2018-08-15 18:32:31.7440,189,67,Kendall T,MIT at Mass Ave / Amherst St,2780,Subscriber

In [129]:
def clean_date(x):
    return x.split('.')[0]

boston_2018_data_clean['start_time'] = boston_2018_data_clean['start_time'].apply(lambda x: clean_date(x))
boston_2018_data_clean['end_time'] = boston_2018_data_clean['end_time'].apply(lambda x: clean_date(x))
boston_2018_data_clean.head(1000000)

,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type
0,2018-01-01 00:16:33,2018-01-01 00:23:01,178,107,MIT Pacific St at Purrington St,Ames St at Main St,643,Subscriber
1,2018-01-01 00:42:00,2018-01-01 00:46:25,78,225,Union Square - Somerville,Cambridge Dept. of Public Works -147 Hampshire...,1581,Subscriber
2,2018-01-01 00:42:44,2018-01-01 01:02:11,16,76,Back Bay T Stop - Dartmouth St at Stuart St,Central Sq Post Office / Cambridge City Hall a...,173,Subscriber
3,2018-01-01 00:56:50,2018-01-01 01:11:06,69,177,Coolidge Corner - Beacon St @ Centre St,University Park,1772,Subscriber
4,2018-01-01 01:07:54,2018-01-01 01:16:02,4,46,Tremont St at E Berkeley St,Christian Science Plaza - Massachusetts Ave at...,1183,Subscriber
...,...,...,...,...,...,...,...,...
999995,2018-08-15 18:25:56,2018-08-15 18:56:06,35,32,Arch St at Franklin St,Landmark Center - Brookline Ave at Park Dr,838,Subscriber
999996,2018-08-15 18:25:55,2018-08-15 18:32:33,139,87,Dana Park,Harvard University Housing - 115 Putnam Ave at...,3189,Subscriber
999997,2018-08-15 18:25:58,2018-08-15 18:32:30,80,178,MIT Stata Center at Vassar St / Main St,MIT Pacific St at Purrington St,99,Subscriber
999998,2018-08-15 18:25:56,2018-08-16 09:18:15,52,36,Newbury St at Hereford St,Copley Square - Dartmouth St at Boylston St,3199,Subscriber
999999,2018-08-15 18:25:59,2018-08-15 18:32:31,189,67,Kendall T,MIT at Mass Ave / Amherst St,2780,Subscriber

In [130]:
def get_date(x):
    return datetime.strptime(x, "%Y-%m-%d %H:%M:%S").date()

def get_weekday(x):
    return datetime.strptime(x, "%Y-%m-%d %H:%M:%S").weekday()

def get_hour(x):
    return datetime.strptime(x, "%Y-%m-%d %H:%M:%S").hour

def get_month(x):
    return datetime.strptime(x, "%Y-%m-%d %H:%M:%S").month

In [134]:
boston_2018_data_clean.reset_index(drop=True)
boston_2018_data_clean['date'] = boston_2018_data_clean['start_time'].apply(lambda x: get_date(x))

In [135]:
boston_2018_data_clean['weekday'] = boston_2018_data_clean['start_time'].apply(lambda x: get_weekday(x))

In [136]:
boston_2018_data_clean['hour'] = boston_2018_data_clean['start_time'].apply(lambda x: get_hour(x))

In [137]:
boston_2018_data_clean['month'] = boston_2018_data_clean['start_time'].apply(lambda x: get_month(x))

In [138]:
boston_2018_data_clean.head(5)

,level_0,index,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type,date,weekday,hour,month
0,0,0,2018-01-01 00:16:33,2018-01-01 00:23:01,178,107,MIT Pacific St at Purrington St,Ames St at Main St,643,Subscriber,2018-01-01,0,0,1
1,1,1,2018-01-01 00:42:00,2018-01-01 00:46:25,78,225,Union Square - Somerville,Cambridge Dept. of Public Works -147 Hampshire...,1581,Subscriber,2018-01-01,0,0,1
2,2,2,2018-01-01 00:42:44,2018-01-01 01:02:11,16,76,Back Bay T Stop - Dartmouth St at Stuart St,Central Sq Post Office / Cambridge City Hall a...,173,Subscriber,2018-01-01,0,0,1
3,3,3,2018-01-01 00:56:50,2018-01-01 01:11:06,69,177,Coolidge Corner - Beacon St @ Centre St,University Park,1772,Subscriber,2018-01-01,0,0,1
4,4,4,2018-01-01 01:07:54,2018-01-01 01:16:02,4,46,Tremont St at E Berkeley St,Christian Science Plaza - Massachusetts Ave at...,1183,Subscriber,2018-01-01,0,1,1
5,5,5,2018-01-01 01:15:59,2018-01-01 01:17:21,31,186,Seaport Hotel - Congress St at Seaport Ln,Congress St at Northern Ave,1793,Subscriber,2018-01-01,0,1,1
6,6,6,2018-01-01 01:35:37,2018-01-01 01:42:35,51,222,Washington St at Lenox St,Troy Boston,60,Subscriber,2018-01-01,0,1,1
7,7,7,2018-01-01 01:35:46,2018-01-01 01:45:11,189,178,Kendall T,MIT Pacific St at Purrington St,371,Subscriber,2018-01-01,0,1,1
8,8,8,2018-01-01 01:45:04,2018-01-01 01:53:40,108,176,Harvard University / SEAS Cruft-Pierce Halls a...,Lesley University,961,Subscriber,2018-01-01,0,1,1
9,9,9,2018-01-01 01:56:58,2018-01-01 02:06:13,185,178,Third at Binney,MIT Pacific St at Purrington St,1286,Subscriber,2018-01-01,0,1,1
10,10,10,2018-01-01 02:01:28,2018-01-01 02:08:09,95,90,Cambridge St - at Columbia St / Webster Ave,Lechmere Station at Cambridge St / First St,1142,Subscriber,2018-01-01,0,2,1
11,11,11,2018-01-01 02:06:06,2018-01-01 02:10:59,218,150,Watermark Seaport - Boston Wharf Rd at Seaport...,State Street at Channel Center,34,Subscriber,2018-01-01,0,2,1
12,12,12,2018-01-01 02:13:16,2018-01-01 02:22:41,49,25,Stuart St at Charles St,South End Library - Tremont St at W Newton St,1790,Subscriber,2018-01-01,0,2,1
13,13,13,2018-01-01 02:13:20,2018-01-01 02:20:04,90,95,Lechmere Station at Cambridge St / First St,Cambridge St - at Columbia St / Webster Ave,1243,Subscriber,2018-01-01,0,2,1
14,14,14,2018-01-01 02:15:04,2018-01-01 02:26:25,150,93,State Street at Channel Center,JFK/UMass T Stop,284,Subscriber,2018-01-01,0,2,1
15,15,15,2018-01-01 02:43:18,2018-01-01 02:52:10,23,72,Boston City Hall - 28 State St,One Broadway / Kendall Sq at Main St / 3rd St,1901,Subscriber,2018-01-01,0,2,1
16,16,16,2018-01-01 05:35:49,2018-01-01 05:43:37,36,4,Copley Square - Dartmouth St at Boylston St,Tremont St at E Berkeley St,1828,Subscriber,2018-01-01,0,5,1
17,17,17,2018-01-01 06:12:34,2018-01-01 06:24:31,119,63,South Boston Library - 646 E Broadway,Dorchester Ave at Gillette Park,1950,Subscriber,2018-01-01,0,6,1
18,18,18,2018-01-01 06:13:58,2018-01-01 06:19:46,130,93,Upham's Corner TEMPORARY WINTER LOCATION,JFK/UMass T Stop,1233,Subscriber,2018-01-01,0,6,1
19,19,19,2018-01-01 06:57:34,2018-01-01 07:00:01,33,32,Kenmore Square,Landmark Center - Brookline Ave at Park Dr,819,Subscriber,2018-01-01,0,6,1
20,20,20,2018-01-01 07:39:29,2018-01-01 07:43:34,40,43,Lewis Wharf at Atlantic Ave,Rowes Wharf at Atlantic Ave,1862,Subscriber,2018-01-01,0,7,1
21,21,21,2018-01-01 07:52:45,2018-01-01 07:57:01,124,133,Curtis Hall - South St at Centre St,Green Street T Stop - Green St at Amory St,1053,Subscriber,2018-01-01,0,7,1
22,22,22,2018-01-01 07:53:37,2018-01-01 07:58:31,25,16,South End Library - Tremont St at W Newton St,Back Bay T Stop - Dartmouth St at Stuart St,1790,Subscriber,2018-01-01,0,7,1
23,23,23,2018-01-01 08:25:51,2018-01-01 08:45:39,121,42,W Broadway at Dorchester St,Boylston St at Arlington St TEMPORARY WINTER L...,363,Subscriber,2018-01-01,0,8,1
24,24,24,2018-01-01 08:55:33,2018-01-01 09:01:12,221,88,Verizon Innovation Hub 10 Ware Street,Inman Square at Vellucci Plaza / Hampshire St,131,Subscriber,2018-01-01,0,8,1
25,25,25,2018-01-01 09:22:12,2018-01-01 09:36:53,119,22,South Boston Library - 646 E Broadway,South Station - 700 Atlantic Ave,453,Subscriber,2018-01-01,0,9,1
26,26,26,2018-01-01 09:25:59,2018-01-01 09:31:32,225,78,Cambridge Dept. of Public Works -147 Hampshire...,Union Square - Somerville,1222,Subscriber,2018-01-01,0,9,1
27,27,27,2018-01-01 09:29:16,2018-01-01 09:40:53,145,73,Rindge Avenue - O'Neill Library,Harvard Square at Brattle St / Eliot St,1893,Subscriber,2018-01-01,0,9,1
28,28,28,2018-01-01 09:38:02,2018-01-01 09:42:35,91,67,One Kendall Square at Hampshire St / Portland St,MIT at Mass Ave / Amherst St,962,Subscriber,2018-01-01,0,9,1
29,29,29,2018-01-01 09:44:56,2018-01-01 09:52:28,46,4,Christian Science Plaza - Massachusetts Ave at...,Tremont St at E Berkeley St,1149,Subscriber,2018-01-01,0,9,1

# Add bike station data

In [139]:
bike_stations = pd.read_csv('resources/current_bluebikes_stations.csv')
bike_stations.head(5)

,Last Updated,May 7th 2021,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Number,Name,Latitude,Longitude,District,Public,Total docks
1,W32006,160 Arsenal,42.36466403,-71.17569387,Watertown,Yes,11
2,A32019,175 N Harvard St,42.363796,-71.129164,Boston,Yes,18
3,S32035,191 Beacon St,42.38032335,-71.10878613,Somerville,Yes,19
4,C32094,2 Hummingbird Lane at Olmsted Green,42.28887,-71.095003,Boston,Yes,17
5,S32023,30 Dane St,42.38100143,-71.10402523,Somerville,Yes,15
6,M32026,359 Broadway - Broadway at Fayette Street,42.370803,-71.104412,Cambridge,Yes,23
7,C32091,645 Summer St,42.34178089,-71.03987017,Boston,Yes,19
8,M32054,699 Mt Auburn St,42.37500235,-71.14871614,Cambridge,Yes,25
9,V32001,7 Acre Park,42.41143223,-71.06823265,Everett,Yes,15

In [140]:
len(bike_stations) - len(bike_stations.dropna())

0

In [141]:
bike_stations.columns = bike_stations.iloc[0]
bike_stations.drop(bike_stations.index[0])

,Number,Name,Latitude,Longitude,District,Public,Total docks
1,W32006,160 Arsenal,42.36466403,-71.17569387,Watertown,Yes,11
2,A32019,175 N Harvard St,42.363796,-71.129164,Boston,Yes,18
3,S32035,191 Beacon St,42.38032335,-71.10878613,Somerville,Yes,19
4,C32094,2 Hummingbird Lane at Olmsted Green,42.28887,-71.095003,Boston,Yes,17
5,S32023,30 Dane St,42.38100143,-71.10402523,Somerville,Yes,15
...,...,...,...,...,...,...,...
368,N32006,West Newton Armory,42.34947178,-71.22000679,Newton,Yes,11
369,A32043,Western Ave at Richardson St,42.36178741,-71.14393111,Boston,Yes,19
370,B32059,Whittier St Health Center,42.33286288,-71.09218862,Boston,Yes,19
371,D32040,Williams St at Washington St,42.306539,-71.107669,Boston,Yes,19
372,S32005,Wilson Square,42.38567579,-71.11412136,Somerville,Yes,15

In [142]:
boston_2018_start_geodata = pd.merge(boston_2018_data_clean, bike_stations[['Name','Latitude', 'Longitude', 'District']], left_on="start_station_name", right_on="Name", how="left")
boston_2018_start_geodata = boston_2018_start_geodata.rename(columns = {'Latitude': 'latitude_start', 'Longitude': 'longitude_start', "District": "district_start"})
boston_2018_start_geodata['start_coordinates'] = list(zip(boston_2018_start_geodata["latitude_start"],boston_2018_start_geodata["longitude_start"]))
del boston_2018_start_geodata['Name']

boston_2018_trip_geodata = pd.merge(boston_2018_start_geodata, bike_stations[['Name','Latitude', 'Longitude', 'District']], left_on="end_station_name", right_on="Name", how="left")
boston_2018_trip_geodata = boston_2018_trip_geodata.rename(columns = {'Latitude': 'latitude_end', 'Longitude': 'longitude_end', "District": "district_end"})
boston_2018_trip_geodata['end_coordinates'] = list(zip(boston_2018_trip_geodata["latitude_end"],boston_2018_trip_geodata["longitude_end"]))
del boston_2018_trip_geodata['Name']

boston_2018_trip_geodata.head(5)

,level_0,index,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type,date,weekday,hour,month,latitude_start,longitude_start,district_start,latitude_end,longitude_end,district_end
0,0,0,2018-01-01 00:16:33,2018-01-01 00:23:01,178,107,MIT Pacific St at Purrington St,Ames St at Main St,643,Subscriber,2018-01-01,0,0,1,42.3595732,-71.10129476,Cambridge,42.3625,-71.08822,Cambridge
1,1,1,2018-01-01 00:42:00,2018-01-01 00:46:25,78,225,Union Square - Somerville,Cambridge Dept. of Public Works -147 Hampshire...,1581,Subscriber,2018-01-01,0,0,1,42.37971603,-71.09391332,Somerville,42.37119728,-71.09759867,Cambridge
2,2,2,2018-01-01 00:42:44,2018-01-01 01:02:11,16,76,Back Bay T Stop - Dartmouth St at Stuart St,Central Sq Post Office / Cambridge City Hall a...,173,Subscriber,2018-01-01,0,0,1,42.34807412,-71.07657015,Boston,42.366426,-71.105495,Cambridge
3,3,3,2018-01-01 00:56:50,2018-01-01 01:11:06,69,177,Coolidge Corner - Beacon St @ Centre St,University Park,1772,Subscriber,2018-01-01,0,0,1,NaN,NaN,NaN,42.36264779,-71.10006094,Cambridge
4,4,4,2018-01-01 01:07:54,2018-01-01 01:16:02,4,46,Tremont St at E Berkeley St,Christian Science Plaza - Massachusetts Ave at...,1183,Subscriber,2018-01-01,0,1,1,42.345392,-71.069616,Boston,42.34366582,-71.08582377,Boston
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,999995,2018-08-15 18:25:56,2018-08-15 18:56:06,35,32,Arch St at Franklin St,Landmark Center - Brookline Ave at Park Dr,838,Subscriber,2018-08-15,2,18,8,42.35533502,-71.05822917,Boston,42.34369056,-71.10235287,Boston
999996,999996,999996,2018-08-15 18:25:55,2018-08-15 18:32:33,139,87,Dana Park,Harvard University Housing - 115 Putnam Ave at...,3189,Subscriber,2018-08-15,2,18,8,42.36178044,-71.10809952,Cambridge,42.366621,-71.114214,Cambridge
999997,999997,999997,2018-08-15 18:25:58,2018-08-15 18:32:30,80,178,MIT Stata Center at Vassar St / Main St,MIT Pacific St at Purrington St,99,Subscriber,2018-08-15,2,18,8,42.36213123,-71.09115601,Cambridge,42.3595732,-71.10129476,Cambridge
999998,999998,999998,2018-08-15 18:25:56,2018-08-16 09:18:15,52,36,Newbury St at Hereford St,Copley Square - Dartmouth St at Boylston St,3199,Subscriber,2018-08-15,2,18,8,42.348717,-71.085954,Boston,42.34992828,-71.07739207,Boston
999999,999999,999999,2018-08-15 18:25:59,2018-08-15 18:32:31,189,67,Kendall T,MIT at Mass Ave / Amherst St,2780,Subscriber,2018-08-15,2,18,8,42.36242784,-71.08495474,Cambridge,42.3581,-71.093198,Cambridge

In [ ]:
len(boston_2018_trip_geodata)-len(boston_2018_trip_geodata.dropna())

In [143]:
boston_2018_trip_geodata_clean = boston_2018_trip_geodata.dropna(axis=0)
boston_2018_trip_geodata_clean.head(10)

,level_0,index,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type,date,weekday,hour,month,latitude_start,longitude_start,district_start,latitude_end,longitude_end,district_end
0,0,0,2018-01-01 00:16:33,2018-01-01 00:23:01,178,107,MIT Pacific St at Purrington St,Ames St at Main St,643,Subscriber,2018-01-01,0,0,1,42.3595732,-71.10129476,Cambridge,42.3625,-71.08822,Cambridge
1,1,1,2018-01-01 00:42:00,2018-01-01 00:46:25,78,225,Union Square - Somerville,Cambridge Dept. of Public Works -147 Hampshire...,1581,Subscriber,2018-01-01,0,0,1,42.37971603,-71.09391332,Somerville,42.37119728,-71.09759867,Cambridge
2,2,2,2018-01-01 00:42:44,2018-01-01 01:02:11,16,76,Back Bay T Stop - Dartmouth St at Stuart St,Central Sq Post Office / Cambridge City Hall a...,173,Subscriber,2018-01-01,0,0,1,42.34807412,-71.07657015,Boston,42.366426,-71.105495,Cambridge
4,4,4,2018-01-01 01:07:54,2018-01-01 01:16:02,4,46,Tremont St at E Berkeley St,Christian Science Plaza - Massachusetts Ave at...,1183,Subscriber,2018-01-01,0,1,1,42.345392,-71.069616,Boston,42.34366582,-71.08582377,Boston
5,5,5,2018-01-01 01:15:59,2018-01-01 01:17:21,31,186,Seaport Hotel - Congress St at Seaport Ln,Congress St at Northern Ave,1793,Subscriber,2018-01-01,0,1,1,42.34881026,-71.04167744,Boston,42.3481,-71.03764,Boston
6,6,6,2018-01-01 01:35:37,2018-01-01 01:42:35,51,222,Washington St at Lenox St,Troy Boston,60,Subscriber,2018-01-01,0,1,1,42.33509899,-71.07903779,Boston,42.343749,-71.062256,Boston
7,7,7,2018-01-01 01:35:46,2018-01-01 01:45:11,189,178,Kendall T,MIT Pacific St at Purrington St,371,Subscriber,2018-01-01,0,1,1,42.36242784,-71.08495474,Cambridge,42.3595732,-71.10129476,Cambridge
8,8,8,2018-01-01 01:45:04,2018-01-01 01:53:40,108,176,Harvard University / SEAS Cruft-Pierce Halls a...,Lesley University,961,Subscriber,2018-01-01,0,1,1,42.377945,-71.116865,Cambridge,42.38674802,-71.11901879,Cambridge
9,9,9,2018-01-01 01:56:58,2018-01-01 02:06:13,185,178,Third at Binney,MIT Pacific St at Purrington St,1286,Subscriber,2018-01-01,0,1,1,42.36544486,-71.08277142,Cambridge,42.3595732,-71.10129476,Cambridge
10,10,10,2018-01-01 02:01:28,2018-01-01 02:08:09,95,90,Cambridge St - at Columbia St / Webster Ave,Lechmere Station at Cambridge St / First St,1142,Subscriber,2018-01-01,0,2,1,42.372969,-71.094445,Cambridge,42.370677,-71.076529,Cambridge

# Adding temperature data

In [ ]:
boston_weather = pd.read_csv('resources/weather_hourly_boston.csv')
boston_weather.head(10)

In [ ]:
len(boston_weather) - len(boston_weather.dropna())

In [ ]:
boston_weather_clean = boston_weather.dropna()
len(boston_weather_clean) - len(boston_weather_clean.dropna())

In [ ]:
boston_weather_clean.reset_index(drop=True)
pd.options.mode.chained_assignment = None
boston_weather_clean['date'] = boston_weather_clean['date_time'].apply(lambda x:get_date(x))
boston_weather_clean['hour'] = boston_weather_clean['date_time'].apply(lambda x:get_hour(x))
boston_weather_clean.head(10)

In [ ]:
boston_2018_trip_geodata_with_temp = pd.merge(boston_2018_trip_geodata_clean, 
                                              boston_weather_clean[['max_temp','min_temp', 'precip', 'date', 'hour']],
                                              on=['date', 'hour'], how="left")
boston_2018_trip_geodata_with_temp.head(5)

In [ ]:
len(boston_2018_trip_geodata_with_temp)-len(boston_2018_trip_geodata_with_temp.dropna())

In [ ]:
boston_2018_trip_geodata_with_temp_clean = boston_2018_trip_geodata_with_temp.dropna()
len(boston_2018_trip_geodata_with_temp_clean)-len(boston_2018_trip_geodata_with_temp_clean.dropna())